FROM golang:1.16-buster as build

RUN apt-get update

RUN apt install -y dirmngr gnupg apt-transport-https software-properties-common ca-certificates curl
RUN curl -fsSL https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add -
RUN add-apt-repository 'deb https://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main'
RUN apt-get update && apt install -y mongodb-org-shell

WORKDIR /service
CMD tail -f /dev/null

FROM build as test
