swagger: "2.0"
info:
  description: |
    An API used to fetch information about dataset recipes.
  version: "1.0.0"
  title: "ONS Recipe API"
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
schemes:
- "http"
parameters:
  recipe_id:
    name: recipe_id
    description: "A unique id for a recipe"
    type: string
    in: path
    required: true
  new_recipe:
    name: recipe
    description: "A new recipe"
    in: body
    required: true
    schema:
      $ref: '#/definitions/AddRecipe'
  recipe_update:
    name: recipe_updates
    description: "Update for existing recipe"
    in: body
    required: true
    schema:
      $ref: '#/definitions/UpdateRecipe'
  instance_id:
    name: instance_id
    description: "An id for an instance in the recipe"
    type: string
    in: path
    required: true
  new_instance:
    name: instance
    description: "A new instance"
    in: body
    required: true
    schema:
      $ref: '#/definitions/AddInstance'
  instance_update:
    name: instance_updates
    description: "Update for instance in existing recipe"
    in: body
    required: true
    schema:
      $ref: '#/definitions/UpdateInstance'
  codelist_id:
    name: codelist_id
    description: "An id for codelist in an instance of a recipe"
    type: string
    in: path
    required: true
  new_codelist:
    name: codelist
    description: "A new codelist"
    in: body
    required: true
    schema:
      $ref: '#/definitions/AddCodelist'
  codelist_update:
    name: codelist_updates
    description: "Update of codelist in instance in existing recipe"
    in: body
    required: true
    schema:
      $ref: '#/definitions/CodeList'
paths:
  /recipes:
    get:
      summary: "Get a list of recipes"
      description: |
        Returns a paged list of recipes
      produces:
      - "application/json"
      responses:
        200:
          description: "A list of recipes"
          schema:
            $ref: '#/definitions/RecipeList'
        500:
          $ref: '#/responses/InternalError'
    post:
      summary: "Create a recipe"
      description: |
        Create a recipe and add to mongo
      parameters:
      - $ref: '#/parameters/new_recipe'
      produces:
      - "application/json"
      responses:
        200:
          description: "A json object of a recipe which has been created"
          schema:
            $ref: '#/definitions/Recipe'
        400:
          description: "An incomplete/invalid recipe entered in request to be added to mongo"
        500:
          $ref: '#/responses/InternalError'
  /recipes/recipe_id:
    get:
      summary: "Get a specific recipe"
      description: |
        Returns a specific recipe
      parameters:
      - $ref: '#/parameters/recipe_id'
      produces:
      - "application/json"
      responses:
        200:
          description: "A specific recipe"
          schema:
            $ref: '#/definitions/Recipe'
        404:
          description: "Recipe not found"
        500:
          $ref: '#/responses/InternalError'
    put:
      summary: "Update a recipe"
      description: |
        Update a recipe by getting the specific recipe by id and update in mongo
      parameters:
      - $ref: '#/parameters/recipe_id' 
      - $ref: '#/parameters/recipe_update'
      produces:
      - "application/json"
      responses:
        200:
          description: "Specific recipe updated successfully with given recipe updates"
        400:
          description: "An incomplete/invalid recipe entered in request to be updated to mongo"
        404:
          description: "Recipe not found"
        500:
          $ref: '#/responses/InternalError'
  /recipes/recipe_id/instances:
    post:
      summary: "Create an instance"
      description: |
        Create an instance in the recipe and add to mongo
      parameters:
      - $ref: '#/parameters/recipe_id'
      - $ref: '#/parameters/new_instance'
      produces:
      - "application/json"
      responses:
        200:
          description: "A json object of specific recipe with new added instance"
          schema:
            $ref: '#/definitions/Recipe'
        400:
          description: "An incomplete/invalid instance entered in request to be added to mongo"
        500:
          $ref: '#/responses/InternalError'
  /recipes/recipe_id/instances/instance_id:
    put:
      summary: "Update an instance"
      description: |
        Update an instance of recipe by getting the specific instance and recipe by id and update in mongo
      parameters:
      - $ref: '#/parameters/recipe_id' 
      - $ref: '#/parameters/instance_id' 
      - $ref: '#/parameters/instance_update'
      produces:
      - "application/json"
      responses:
        200:
          description: "Specific recipe updated successfully with given instance updates"
        400:
          description: "An incomplete/invalid instance entered in request to be updated to mongo"
        404:
          description: "Recipe not found"
        500:
          $ref: '#/responses/InternalError'
  /recipes/recipe_id/instances/instance_id/codelists:
    post:
      summary: "Create a codelist"
      description: |
        Create a codelist for an instance in recipe and add to mongo
      parameters:
      - $ref: '#/parameters/recipe_id'
      - $ref: '#/parameters/instance_id'
      - $ref: '#/parameters/new_codelist'
      produces:
      - "application/json"
      responses:
        200:
          description: "A json object of specific recipe with new added codelist in specific instance"
          schema:
            $ref: '#/definitions/Recipe'
        400:
          description: "An incomplete/invalid codelist entered in request to be added to mongo"
        500:
          $ref: '#/responses/InternalError'
  /recipes/recipe_id/instances/instance_id/codelists/codelist_id:
    put:
      summary: "Update a codelist"
      description: |
        Update an codelist of a specific instance in the specific recipe and update in mongo
      parameters:
      - $ref: '#/parameters/recipe_id' 
      - $ref: '#/parameters/instance_id' 
      - $ref: '#/parameters/codelist_id'
      - $ref: '#/parameters/codelist_update'
      produces:
      - "application/json"
      responses:
        200:
          description: "Specific recipe updated successfully with given codelist updates"
        400:
          description: "An incomplete/invalid codelist entered in request to be updated to mongo"
        500:
          $ref: '#/responses/InternalError'
  
responses:
  InternalError:
    description: "Failed to process the request due to an internal error"
definitions:
  RecipeList:
    type: object
    description: "A list of recipes"
    properties:
      count:
        type: number
        readOnly: true
        description: "The number of recipes returned"
      total_count:
        type: number
        readOnly: true
        description: "The total number of recipes"
      offset:
        type: number
        readOnly: true
        description: "The first row of resources to retrieve, starting at 0. Use this parameter as a pagination mechanism along with the limit parameter"
      limit:
        type: number
        readOnly: true
        description: "The number of items per page"
      items:
        type: array
        readOnly: true
        items:
          $ref: '#/definitions/Recipe'
  Recipe:
    type: object
    description: "An object returned for a recipe"
    properties:
      id:
        type: string
        description: "A unique id for the recipe"
        example: "b944be78-f56d-409b-9ebd-ab2b77ffe187"
      alias:
        type: string
        description: "An alias for the recipe"
        example: "CPI COICOP"
      format:
        type: string
        description: "The recipe format"
        enum: ["v4"]
      input_files:
        type: array
        items: 
          $ref: '#/definitions/InputFile'
      output_instances:
          type: array
          description: "A list of all instances created using this recipe"
          items:
            $ref: '#/definitions/Instance'
  InputFile:
    type: object
    required: [description]
    description: "An input file"
    properties:
      description: 
        type: string
        description: "The description of the input file"
        example: "CPI COICOP v4"
  Instance:
    type: object
    description: "An instance represents a single dataset"
    properties:
      dataset_id:
        type: string
        description: "A unique id for a dataset"
        example: "931a8a2a-0dc8-42b6-a884-7b6054ed3b68"
      editions:
        type: array
        required: [items]
        description: "Types of editions within the dataset"
        items:
          type: string
          example: "Time-series"
      title:
        type: string
        description: "The title for the dataset"
        example: "UK consumer price inflation"
      code_lists:
        type: array
        description: "A list of all code lists within this instance"
        items:
          $ref: '#/definitions/CodeList'
  CodeList:
    type: object
    description: "A code list refers to a list of all possible codes"
    properties:
      id:
        type: string
        description: "A unique id for a single code list"
        example: "e44de4c4-d39e-4e2f-942b-3ca10584d078"
      name:
        type: string
        description: "The name of the codelist"
        example: "calendar-years"
      href:
        type: string
        description: "A URL to the code list"
        example: "http://localhost/code-lists/e44de4c4-d39e-4e2f-942b-3ca10584d0782"
      isHierarchy:
        type: boolean
        description: "A bool to inform if there is hierarchy for codelist"
  AddRecipe:
    required:
      - alias
      - format
      - input_files
      - output_instances
    allOf: 
      - $ref: '#/definitions/Recipe'
    properties:
      output_instances:
          type: array
          description: "A list of all instances created using this recipe"
          items:
            $ref: '#/definitions/AddInstance'
  UpdateRecipe:
    allOf: 
      - $ref: '#/definitions/Recipe'
    properties:
      output_instances:
          type: array
          description: "A list of all instances created using this recipe"
          items:
            $ref: '#/definitions/AddInstance'
  AddInstance:
    required:
      - dataset_id
      - editions
      - title
      - code_lists
    allOf: 
      - $ref: '#/definitions/Instance'
    properties:
      code_lists:
        type: array
        description: "A list of all code lists within this instance"
        items:
          $ref: '#/definitions/AddAllCodelist'
  UpdateInstance:
    allOf: 
      - $ref: '#/definitions/Instance'
    properties:
      code_lists:
        type: array
        description: "A list of all code lists within this instance"
        items:
          $ref: '#/definitions/AddAllCodelist'
  AddAllCodelist:
    required:
      - id
      - name
      - isHierarchy
      - href
    allOf: 
      - $ref: '#/definitions/CodeList'
  AddCodelist:
    required:
      - id
      - name
      - isHierarchy
    allOf: 
      - $ref: '#/definitions/CodeList'