---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.9-bookworm

inputs:
  - name: dp-recipe-api

outputs:
  - name: build

run:
  path: dp-recipe-api/ci/scripts/build.sh
