---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.9.1

inputs:
  - name: dp-recipe-api
    path: go/src/github.com/ONSdigital/dp-recipe-api

outputs:
  - name: build

run:
  path: go/src/github.com/ONSdigital/dp-recipe-api/ci/scripts/build.sh
